version: '3'
services:
  selenoid:
    image: aerokube/selenoid:latest-release
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      # главный трюк: даём Selenoid доступ к сокету Docker,
      # чтобы он мог стартовать контейнеры с браузерами
      - "/var/run/docker.sock:/var/run/docker.sock"
      # наш конфиг с браузерами
      - "./config:/etc/selenoid:ro"
      # куда складывать видео и логи
      - "./config/video:/opt/selenoid/video"
      - "./config/logs:/opt/selenoid/logs"
    environment:
      # помогает видео-контейнеру писать файлы на host (особенно в Windows)
      - OVERRIDE_VIDEO_OUTPUT_DIR=/opt/selenoid/video
    command:
      [
        "-conf", "/etc/selenoid/browsers.json",
        "-video-output-dir", "/opt/selenoid/video",
        "-log-output-dir", "/opt/selenoid/logs",
        "-limit", "5"  # параллельные сессии, подберите под свою машину
      ]
