name: Run tests

on:
  workflow_call:
    inputs:
      package:
        description: api | ui
        required: true
        type: string

jobs:
  validate-checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '21'
          cache: maven

      # Pick Maven wrapper if complete; else install Maven
      - name: Choose Maven (wrapper or system)
        run: |
          if [ -f mvnw ] && [ -f .mvn/wrapper/maven-wrapper.jar ] && [ -f .mvn/wrapper/maven-wrapper.properties ]; then
            sed -i 's/\r$//' mvnw || true
            chmod +x mvnw || true
            CMD=./mvnw
          else
            echo "Maven Wrapper missing/incomplete. Installing Maven..."
            sudo apt-get update
            sudo apt-get install -y maven
            CMD=mvn
          fi
          echo "MVN_CMD=$CMD" >> "$GITHUB_ENV"
          $CMD -v
          java -version
          
      - name: Ensure checkstyle.xml exists at repo root
        shell: bash
        run: |
          set -Eeuo pipefail
          if [[ ! -f checkstyle.xml ]]; then
            echo "Creating minimal checkstyle.xml at repo root"
            # IMPORTANT: The heredoc delimiter and body must be exactly as shown—no extra spaces or quotes
            cat > checkstyle.xml <<'XML'
          <?xml version="1.0"?>
          <!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">
          <module name="Checker">
          <property name="charset" value="UTF-8"/>
          <!-- Start minimal; expand later -->
          <module name="TreeWalker"/>
          </module>
          XML
            fi



      - name: Validate Checkstyle (show violations)
        run: mvn -B -V -e -Dcheckstyle.consoleOutput=true -Dcheckstyle.failOnViolation=false validate

      - name: Upload Checkstyle report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          # make the name unique across api/ui, jobs, and reruns
          name: checkstyle-report-${{ inputs.package }}-${{ github.job }}-${{ github.run_attempt }}
          path: |
            **/target/checkstyle-result.xml
            **/target/checkstyle-cachefile
          if-no-files-found: ignore
          compression-level: 6
          overwrite: false

  run-tests:
    needs: validate-checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: maven

      # Repeat chooser in this job (env doesn’t persist across jobs)
      # after actions/checkout and setup-java
      - name: Choose Maven (wrapper or system)
        run: |
          set -e
          if [ -f mvnw ] && [ -f .mvn/wrapper/maven-wrapper.jar ] && [ -f .mvn/wrapper/maven-wrapper.properties ]; then
            # normalize wrapper for Linux
            sed -i 's/\r$//' mvnw || true
            chmod +x mvnw || true
            CMD=./mvnw
          else
            echo "Maven Wrapper missing/incomplete. Installing Maven..."
            sudo apt-get update
            sudo apt-get install -y maven
            CMD=mvn
          fi
          echo "MVN_CMD=$CMD" >> "$GITHUB_ENV"
          echo "Using Maven: $CMD"
          $CMD -v
          java -version

      # ... TeamCity setup step(s) ...

      - name: Run tests
        run: |
          mvn -B -Dcheckstyle.failOnViolation=false \
              -Dtest="com.example.teamcity.${{ inputs.package }}.**" \
              -Dgroups=Regression test