name: Run tests

on:
  workflow_call:
    inputs:
      package:
        description: api | ui
        required: true
        type: string

permissions:
  contents: write

jobs:
  validate-checkstyle:
    runs-on: ubuntu-latest
    continue-on-error: true       # ← even if the step fails, this job won’t block others
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '21'
          cache: maven
      - name: Choose Maven (wrapper or system)
        run: |
          if [ -f mvnw ] && [ -f .mvn/wrapper/maven-wrapper.jar ] && [ -f .mvn/wrapper/maven-wrapper.properties ]; then
            sed -i 's/\r$//' mvnw || true; chmod +x mvnw || true; echo "MVN_CMD=./mvnw" >> $GITHUB_ENV
          else
            sudo apt-get update && sudo apt-get install -y maven; echo "MVN_CMD=mvn" >> $GITHUB_ENV
          fi
      - name: Run Checkstyle (do not fail CI)
        # failOnViolation=false makes the step exit 0; job-level continue-on-error is a second safety net
        run: ${{ env.MVN_CMD }} -B -DskipTests -Dcheckstyle.consoleOutput=true -Dcheckstyle.failOnViolation=false validate
      - name: Upload Checkstyle report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report-${{ github.run_attempt }}
          path: |
            **/target/checkstyle-result.xml
            **/target/checkstyle-cachefile
          if-no-files-found: ignore
          overwrite: true

  run-tests:
    needs: validate-checkstyle
    if: ${{ always() }}
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '21'
          cache: maven

      # Start ONLY TeamCity + finish first-start (your composite)
      - name: TeamCity Setup
        id: setup
        uses: ./.github/actions/teamcity-setup

      # Start Selenoid in this job
      - name: Start Selenoid
        uses: Xotabu4/selenoid-github-action@v2

      # Run UI tests against Selenoid
      - name: Run UI tests (remote to Selenoid)
        run: |
          # use wrapper if present, else system maven
          if [ -f mvnw ]; then MVN=./mvnw; else MVN=mvn; fi
          $MVN -B \
            -Dcheckstyle.skip=true \
            -Dselenide.remote=http://localhost:4444/wd/hub \
            -Dselenide.browser=chrome \
            -Dselenide.headless=true \
            -Dselenide.baseUrl=http://host.docker.internal:8111 \
            -Dgroups=Regression \
            -Dtest="teamcity.ui.**" \
            test

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ inputs.package }}-${{ github.run_attempt }}
          path: |
            **/target/surefire-reports/**
            **/target/failsafe-reports/**
          if-no-files-found: ignore

