name: CI Pipeline with Swagger and Allure Reports

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to run (e.g., api)'
        required: true
        default: 'api'

jobs:
  runSwaggerCoverage:
    runs-on: ubuntu-latest
    if: ${{ inputs.package == 'api' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'  # Match your project’s Java version
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean test  # Generates coverage data via SwaggerCoverageRestAssured

      - name: Run Swagger Coverage
        continue-on-error: true
        run: |
          chmod +x .swagger-coverage-commandline/bin/swagger-coverage
          .swagger-coverage-commandline/bin/swagger-coverage -s "http://${{ env.HOST }}/app/rest/swagger.json" -i target/swagger-coverage-output
        env:
          HOST: ${{ secrets.TEAMCITY_HOST }}

      - name: Save Swagger Coverage
        uses: actions/upload-artifact@v4
        if: ${{ inputs.package == 'api' }}
        with:
          name: swagger-coverage
          path: |
            target/swagger-coverage-output/swagger-coverage-report.html
            target/swagger-coverage-output/swagger-coverage-results.json

      - name: Load Test Report History
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build Test Report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: target/allure-results
          subfolder: ${{ inputs.package }}

      - name: Publish Test Report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: gh-pages/allure-history