name: TeamCity Deployment
on:
  push:
    branches: [ "*" ]

permissions:
  contents: write

jobs:
  backend:
    uses: ./.github/workflows/backend-stage.yml
  frontend:
    uses: ./.github/workflows/frontend-stage.yml
  automation-api:
    needs: [backend, frontend]
    uses: ./.github/workflows/automation.yml
    with:
      package: api
  automation-ui:
    needs: [backend, frontend]
    uses: ./.github/workflows/automation.yml
    with:
      package: ui
